config:
  BinderHub:
    auth_enabled: true

jupyterhub:
  cull:
    # don't cull authenticated users
    users: False
  hub:
    redirectToServer: false
    config:
      BinderSpawner:
        auth_enabled: false
    services:
      binder:
        oauth_no_confirm: true
        oauth_redirect_uri: "https://mybinder.org/v2/gh/tth030/SM_ESR_isostasy/main?labpath=start.ipynb/oauth_callback"
        oauth_client_id: "binder-oauth-client-test"

  singleuser:
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser

  auth: {}
